image:
  repository: enz2g/webapp
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: bradsapp.local
  tls: true # set to true if you want to use TLS locally

config:
  appVersion: "v1.0.0"
