apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    app: {{ include "webapp.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "webapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "webapp.name" . }}
    spec:
      containers:
        - name: {{ include "webapp.name" . }}
          image: "{{ .Values.image.repository | default "enz2g/webapp" }}:{{ .Values.image.tag | default "latest"}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "webapp.fullname" . }}-config
                  
