name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - '.github/workflows/docker-build.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app               # 👈 This sets the working directory for Docker build
          file: ./app/Dockerfile       # 👈 Explicit Dockerfile path (optional if default)
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/webapp:latest
            ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

