name: Build & Publish Helm Chart

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v4
        with:
          ref: main   # ensures we're on main, not detached HEAD

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Lint Helm chart
        run: helm lint ./helmchart

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm package ./helmchart --destination packaged

      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-chart
          path: packaged/*.tgz

      - name: Create or update Helm repo index
        run: |
          mkdir -p docs
          mv ./packaged/*.tgz ./docs/
          helm repo index docs --url https://$GITHUB_REPOSITORY_OWNER.github.io/$(basename $GITHUB_REPOSITORY)

      - name: Commit and push updated Helm repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Publish Helm chart $GITHUB_REF_NAME" || echo "No changes to commit"
          git push origin main
